In [2]:
import arviz as az
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pymc3 as pm
import theano
import xarray as xr
from statistics import NormalDist

print(f"Running on PyMC3 v{pm.__version__}")

Running on PyMC3 v3.11.2

In [3]:
%config InlineBackend.figure_format = 'retina'
az.style.use("arviz-darkgrid")

In [8]:
#ovl for vat_tms 
vat_tms_stats=pd.read_csv('vat_tms_traces.csv')
vat_tms_stats

      Unnamed: 0      a(0)      a(1)      v(0)      v(1)      t(0)      t(1)
0              0  3.906558  4.484750  1.075796  1.085994  0.101848  0.048190
1              1  3.896119  4.474380  1.085839  1.140028  0.092625  0.062295
2              2  3.931675  4.342772  1.153514  1.115587  0.088824  0.096467
3              3  3.867738  4.467295  1.091146  1.080362  0.116369  0.048009
4              4  3.698273  4.279366  1.048928  1.093229  0.146883  0.097850
...          ...       ...       ...       ...       ...       ...       ...
3595        3595  3.951008  4.334985  1.216647  1.048905  0.080983  0.058068
3596        3596  3.805018  4.469545  1.138159  1.108001  0.133438  0.078565
3597        3597  3.876097  4.435064  1.110650  1.054234  0.115694  0.065496
3598        3598  3.756263  4.485071  1.135440  1.069351  0.157252  0.023396
3599        3599  4.048534  4.536111  1.121387  1.108759  0.072252  0.068359

[3600 rows x 7 columns]

In [12]:
v_mu_sham=vat_tms_stats['v(0)'].mean()
v_sigma_sham=vat_tms_stats['v(0)'].std()

v_mu_tms=vat_tms_stats['v(1)'].mean()
v_sigma_tms=vat_tms_stats['v(1)'].std()

print ("Beta TMS =/0") 
ovl_v_tms_sham=NormalDist(mu=v_mu_tms, sigma=v_sigma_tms).overlap(NormalDist(mu=v_mu_sham, sigma=v_sigma_sham))
print (ovl_v_tms_sham)

Beta TMS =/0
0.6780875020257844

In [10]:
a_mu_sham=vat_tms_stats['a(0)'].mean()
a_sigma_sham=vat_tms_stats['a(0)'].std()

a_mu_tms=vat_tms_stats['a(1)'].mean()
a_sigma_tms=vat_tms_stats['a(1)'].std()

print ("Beta TMS =/0") 
ovl_a_tms_sham=NormalDist(mu=a_mu_tms, sigma=a_sigma_tms).overlap(NormalDist(mu=a_mu_sham, sigma=a_sigma_sham))
print (ovl_a_tms_sham)

Beta TMS =/0
0.036142861734477005

In [13]:
t_mu_sham=vat_tms_stats['t(0)'].mean()
t_sigma_sham=vat_tms_stats['t(0)'].std()

t_mu_tms=vat_tms_stats['t(1)'].mean()
t_sigma_tms=vat_tms_stats['t(1)'].std()

print ("Beta TMS =/0") 
ovl_t_tms_sham=NormalDist(mu=t_mu_tms, sigma=t_sigma_tms).overlap(NormalDist(mu=t_mu_sham, sigma=t_sigma_sham))
print (ovl_t_tms_sham)

Beta TMS =/0
0.49965988728736255

In [16]:
#ovl for vat_tms_coh
vat_tms_coh_stats=pd.read_csv('vat_tms_coh_traces.csv')
vat_tms_coh_stats

,Unnamed: 0,a(0.05.0),a(0.05.1),a(0.15.0),a(0.15.1),v(0.05.0),v(0.05.1),v(0.15.0),v(0.15.1),t(0.05.0),t(0.05.1),t(0.15.0),t(0.15.1)
0,0,4.249955,4.659089,3.583235,3.713975,0.896391,0.933569,1.244076,1.319893,0.064276,0.095268,0.189780,0.242672
1,1,4.282116,4.703866,3.449681,3.664424,0.938727,0.945984,1.313634,1.217571,0.038310,0.083774,0.216662,0.201139
2,2,4.430907,4.713615,3.556738,3.379484,0.946334,0.958468,1.371044,1.237974,0.031486,0.081945,0.171252,0.308761
3,3,4.074249,4.713671,3.622075,3.532356,0.837142,0.877813,1.332184,1.252299,0.074131,0.052242,0.159436,0.279526
4,4,4.123563,4.461885,3.615472,3.750611,0.870904,0.906930,1.343301,1.208766,0.055069,0.088116,0.173722,0.211867
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,3595,4.436141,4.802590,3.548861,3.978991,1.002725,0.970125,1.315179,1.275899,0.060034,0.025077,0.195453,0.143192
3596,3596,4.283517,4.875507,3.432033,3.855511,0.925840,0.971721,1.348909,1.326390,0.065048,0.054712,0.236006,0.201370
3597,3597,4.009906,4.812518,3.652735,4.073834,0.897864,0.953120,1.387887,1.270272,0.114408,0.072468,0.184761,0.150993
3598,3598,4.341664,4.658989,3.617245,3.697907,0.951162,0.910910,1.397131,1.196397,0.080818,0.084352,0.211543,0.192487
3599,3599,4.395519,5.001239,3.618918,3.773064,0.891438,1.029334,1.277443,1.308281,0.019300,0.061511,0.177101,0.244780

In [18]:
v_mu_sham_15=vat_tms_coh_stats['v(0.15.0)'].mean()
v_sigma_sham_15=vat_tms_coh_stats['v(0.15.0)'].std()

v_mu_tms_15=vat_tms_coh_stats['v(0.15.1)'].mean()
v_sigma_tms_15=vat_tms_coh_stats['v(0.15.1)'].std()

print ("High precision: Sham vs TMS") 
ovl_v_tms_sham_15=NormalDist(mu=v_mu_tms_15, sigma=v_sigma_tms_15).overlap(NormalDist(mu=v_mu_sham_15, sigma=v_sigma_sham_15))
print (ovl_v_tms_sham_15)

v_mu_sham_05=vat_tms_coh_stats['v(0.05.0)'].mean()
v_sigma_sham_05=vat_tms_coh_stats['v(0.05.0)'].std()

v_mu_tms_05=vat_tms_coh_stats['v(0.05.1)'].mean()
v_sigma_tms_15=vat_tms_coh_stats['v(0.15.1)'].std()

print ("Low precision: Sham vs TMS") 
ovl_v_tms_sham_05=NormalDist(mu=v_mu_tms_05, sigma=v_sigma_tms_15).overlap(NormalDist(mu=v_mu_sham_05, sigma=v_sigma_sham_05))
print (ovl_v_tms_sham_05)

High precision: Sham vs TMS
0.6927259415243732
Low precision: Sham vs TMS
0.6218675324079943

In [20]:
a_mu_sham_15=vat_tms_coh_stats['a(0.15.0)'].mean()
a_sigma_sham_15=vat_tms_coh_stats['a(0.15.0)'].std()

a_mu_tms_15=vat_tms_coh_stats['a(0.15.1)'].mean()
a_sigma_tms_15=vat_tms_coh_stats['a(0.15.1)'].std()

print ("High precision: Sham vs TMS") 
ovl_a_tms_sham_15=NormalDist(mu=a_mu_tms_15, sigma=a_sigma_tms_15).overlap(NormalDist(mu=a_mu_sham_15, sigma=a_sigma_sham_15))
print (ovl_a_tms_sham_15)

a_mu_sham_05=vat_tms_coh_stats['a(0.05.0)'].mean()
a_sigma_sham_05=vat_tms_coh_stats['a(0.05.0)'].std()

a_mu_tms_05=vat_tms_coh_stats['a(0.05.1)'].mean()
a_sigma_tms_15=vat_tms_coh_stats['a(0.15.1)'].std()

print ("Low precision: Sham vs TMS") 
ovl_a_tms_sham_05=NormalDist(mu=a_mu_tms_05, sigma=a_sigma_tms_15).overlap(NormalDist(mu=a_mu_sham_05, sigma=a_sigma_sham_05))
print (ovl_a_tms_sham_05)

High precision: Sham vs TMS
0.5253599383982022
Low precision: Sham vs TMS
0.09070693259741791

In [19]:
t_mu_sham_15=vat_tms_coh_stats['t(0.15.0)'].mean()
t_sigma_sham_15=vat_tms_coh_stats['t(0.15.0)'].std()

t_mu_tms_15=vat_tms_coh_stats['t(0.15.1)'].mean()
t_sigma_tms_15=vat_tms_coh_stats['t(0.15.1)'].std()

print ("High precision: Sham vs TMS") 
ovl_t_tms_sham_15=NormalDist(mu=t_mu_tms_15, sigma=t_sigma_tms_15).overlap(NormalDist(mu=t_mu_sham_15, sigma=t_sigma_sham_15))
print (ovl_t_tms_sham_15)

t_mu_sham_05=vat_tms_coh_stats['t(0.05.0)'].mean()
t_sigma_sham_05=vat_tms_coh_stats['t(0.05.0)'].std()

t_mu_tms_05=vat_tms_coh_stats['t(0.05.1)'].mean()
t_sigma_tms_15=vat_tms_coh_stats['t(0.15.1)'].std()

print ("Low precision: Sham vs TMS") 
ovl_t_tms_sham_05=NormalDist(mu=t_mu_tms_05, sigma=t_sigma_tms_15).overlap(NormalDist(mu=t_mu_sham_05, sigma=t_sigma_sham_05))
print (ovl_t_tms_sham_05)

High precision: Sham vs TMS
0.6809198399901126
Low precision: Sham vs TMS
0.7823479466752957

In [21]:
#ovl for vat_tms_pdi
vat_tms_pdi_stats=pd.read_csv('vat_tms_pdi_traces.csv')
vat_tms_pdi_stats

,Unnamed: 0,a(high_pdi.0),a(high_pdi.1),a(low_pdi.0),a(low_pdi.1),v(high_pdi.0),v(high_pdi.1),v(low_pdi.0),v(low_pdi.1),t(high_pdi.0),t(high_pdi.1),t(low_pdi.0),t(low_pdi.1)
0,0,3.677790,4.342727,4.027776,4.428019,1.242726,1.081101,1.095564,1.176369,0.224331,0.123981,0.070430,0.050978
1,1,3.758743,4.219152,3.482182,4.243961,1.143046,0.953432,1.018707,1.109138,0.150081,0.103659,0.156285,0.106241
2,2,3.718505,4.273712,3.802690,4.291177,1.165436,1.016569,1.136791,1.123890,0.203655,0.082023,0.098344,0.082704
3,3,3.845631,4.225040,3.925076,4.452715,1.228598,1.017724,1.018829,1.149856,0.187956,0.138633,0.087151,0.052058
4,4,3.652260,4.209051,3.462284,4.470526,1.237936,1.043190,1.069533,1.186723,0.213044,0.139926,0.201713,0.109386
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,3595,3.956274,4.391383,3.715169,4.248286,1.176955,1.058327,1.136096,1.133114,0.143535,0.080531,0.120706,0.120385
3596,3596,3.827693,4.420092,3.886457,4.256707,1.167219,0.997562,1.105224,1.158384,0.189655,0.061543,0.113289,0.112921
3597,3597,3.994906,4.074075,3.603944,4.252052,1.247683,0.980580,1.027567,1.088609,0.146939,0.171662,0.136619,0.078981
3598,3598,3.963374,4.278326,3.784086,4.365126,1.356507,1.052516,1.069177,1.202120,0.162670,0.141581,0.151114,0.106726
3599,3599,3.733994,3.978033,3.800643,4.414882,1.145442,0.970039,1.114336,1.208445,0.175359,0.170615,0.105278,0.094393

In [23]:
v_mu_sham_lowpdi=vat_tms_pdi_stats['v(low_pdi.0)'].mean()
v_sigma_sham_lowpdi=vat_tms_pdi_stats['v(low_pdi.0)'].std()

v_mu_tms_lowpdi=vat_tms_pdi_stats['v(low_pdi.1)'].mean()
v_sigma_tms_lowpdi=vat_tms_pdi_stats['v(low_pdi.1)'].std()

print ("Low PDI: Sham vs TMS") 
ovl_v_tms_sham_lowpdi=NormalDist(mu=v_mu_tms_lowpdi, sigma=v_sigma_tms_lowpdi).overlap(NormalDist(mu=v_mu_sham_lowpdi, sigma=v_sigma_sham_lowpdi))
print (ovl_v_tms_sham_lowpdi)

v_mu_sham_highpdi=vat_tms_pdi_stats['v(high_pdi.0)'].mean()
v_sigma_sham_highpdi=vat_tms_pdi_stats['v(high_pdi.0)'].std()

v_mu_tms_highpdi=vat_tms_pdi_stats['v(high_pdi.1)'].mean()
v_sigma_tms_highpdi=vat_tms_pdi_stats['v(high_pdi.1)'].std()

print ("High PDI: Sham vs TMS") 
ovl_v_tms_sham_highpdi=NormalDist(mu=v_mu_tms_highpdi, sigma=v_sigma_tms_highpdi).overlap(NormalDist(mu=v_mu_sham_highpdi, sigma=v_sigma_sham_highpdi))
print (ovl_v_tms_sham_highpdi)


print ("Sham: Low PDI vs High PDI") 
ovl_v_sham_pdi=NormalDist(mu=v_mu_sham_highpdi, sigma=v_sigma_sham_highpdi).overlap(NormalDist(mu=v_mu_sham_lowpdi, sigma=v_sigma_sham_lowpdi))
print (ovl_v_sham_pdi)


print ("TMS: Low PDI vs High PDI") 
ovl_v_tms_pdi=NormalDist(mu=v_mu_tms_highpdi, sigma=v_sigma_tms_highpdi).overlap(NormalDist(mu=v_mu_tms_lowpdi, sigma=v_sigma_tms_lowpdi))
print (ovl_v_tms_pdi)

Low PDI: Sham vs TMS
0.5368541963989806
High PDI: Sham vs TMS
0.07098851678871976
Sham: Low PDI vs High PDI
0.3181389231183984
TMS: Low PDI vs High PDI
0.121651721641867

In [27]:
#ovl for vat_tms_caps
vat_tms_caps_stats=pd.read_csv('vat_tms_caps_traces.csv')
vat_tms_caps_stats

,Unnamed: 0,a(high_caps.0),a(high_caps.1),a(low_caps.0),a(low_caps.1),v(high_caps.0),v(high_caps.1),v(low_caps.0),v(low_caps.1),t(high_caps.0),t(high_caps.1),t(low_caps.0),t(low_caps.1)
0,0,3.828870,3.913077,3.820702,4.410853,1.169189,1.048107,1.169010,1.081943,0.156787,0.101340,0.141973,0.134914
1,1,3.815198,4.155646,3.758188,4.345416,1.172268,1.106947,1.140631,1.045600,0.168574,0.095592,0.147437,0.103961
2,2,3.894175,4.207425,3.835478,4.609796,1.225302,1.140625,1.063313,1.085274,0.161653,0.089095,0.084572,0.092949
3,3,3.839556,3.894441,3.678086,4.522027,1.108179,1.061433,1.078252,1.122810,0.127597,0.171215,0.122432,0.088180
4,4,3.789312,3.577266,3.793677,4.433671,1.127386,1.136090,1.108726,1.010610,0.117598,0.253528,0.097358,0.082525
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,3595,3.670229,4.007711,3.742048,4.857955,1.204764,1.166307,1.114290,1.090996,0.180687,0.145720,0.100763,0.085182
3596,3596,3.805381,3.674029,3.957174,4.488875,1.143351,1.042226,1.175648,1.113584,0.133685,0.253951,0.107994,0.154170
3597,3597,4.017660,3.651869,3.869726,4.394401,1.248469,1.073052,1.151884,1.037899,0.118751,0.197142,0.102422,0.137190
3598,3598,4.013547,3.852466,3.962589,4.343546,1.244629,1.133860,1.165911,1.008236,0.110231,0.170229,0.098074,0.101653
3599,3599,3.853440,3.957656,3.764252,4.375699,1.107237,1.110067,1.027539,1.140426,0.125353,0.155344,0.073343,0.165762

In [28]:
v_mu_sham_lowcaps=vat_tms_caps_stats['v(low_caps.0)'].mean()
v_sigma_sham_lowcaps=vat_tms_caps_stats['v(low_caps.0)'].std()

v_mu_tms_lowcaps=vat_tms_caps_stats['v(low_caps.1)'].mean()
v_sigma_tms_lowcaps=vat_tms_caps_stats['v(low_caps.1)'].std()

print ("Low CAPS: Sham vs TMS") 
ovl_v_tms_sham_lowcaps=NormalDist(mu=v_mu_tms_lowcaps, sigma=v_sigma_tms_lowcaps).overlap(NormalDist(mu=v_mu_sham_lowcaps, sigma=v_sigma_sham_lowcaps))
print (ovl_v_tms_sham_lowcaps)

v_mu_sham_highcaps=vat_tms_caps_stats['v(high_caps.0)'].mean()
v_sigma_sham_highcaps=vat_tms_caps_stats['v(high_caps.0)'].std()

v_mu_tms_highcaps=vat_tms_caps_stats['v(high_caps.1)'].mean()
v_sigma_tms_highcaps=vat_tms_caps_stats['v(high_caps.1)'].std()

print ("High CAPS: Sham vs TMS") 
ovl_v_tms_sham_highcaps=NormalDist(mu=v_mu_sham_highcaps, sigma=v_sigma_sham_highcaps).overlap(NormalDist(mu=v_mu_sham_highcaps, sigma=v_sigma_sham_highcaps))
print (ovl_v_tms_sham_highcaps)


print ("Sham: Low PDI vs High PDI") 
ovl_v_sham_caps=NormalDist(mu=v_mu_sham_highpdi, sigma=v_sigma_sham_highpdi).overlap(NormalDist(mu=v_mu_sham_lowcaps, sigma=v_sigma_sham_lowcaps))
print (ovl_v_sham_caps)


print ("TMS: Low PDI vs High PDI") 
ovl_v_tms_caps=NormalDist(mu=v_mu_tms_highcaps, sigma=v_sigma_tms_highcaps).overlap(NormalDist(mu=v_mu_tms_lowcaps, sigma=v_sigma_tms_lowcaps))
print (ovl_v_tms_pdi)

Low CAPS: Sham vs TMS
0.7260542792330935
High CAPS: Sham vs TMS
1.0
Sham: Low PDI vs High PDI
0.4518721969355439
TMS: Low PDI vs High PDI
0.121651721641867